### ISSUE TITLE
ClassCastException in ReflectionUtils.java:64

### ISSUE THREAD

**Issue by dulleh** [jasminb/jsonapi-converter#110]
Hi, I'm having this problem and it seems to have shown up rather randomly (all tests were working before, now only the Genre test seems to be). The relevant code is below, essentially trying to instantiate a `ResourceConverter` is giving a `ClassCastException`. I've tried commenting out the Relationship stuff and the code then works, so I suspect it's something to do with the `Anime` class. I'm not very knowledgeable on reflection, so I'm not really sure as to what to do from here.

The code is Kotlin, but it also fails when written in Java.

fails:

    @Test
    @Throws(Exception::class)
    fun animeStaffTest () {
        val resourceConverter = ResourceConverter(AnimeStaff::class.java)
		.
		.
	}

passes:

    @Test
    @Throws(Exception::class)
    fun genresTest () {
        val resourceConverter = ResourceConverter(Genre::class.java)
		.
		.
	}

AnimeStaff.kt:

```
package app.youkai.data.models

import com.github.jasminb.jsonapi.Links
import com.github.jasminb.jsonapi.annotations.Relationship
import com.github.jasminb.jsonapi.annotations.RelationshipLinks
import com.github.jasminb.jsonapi.annotations.Type

@Type("animeStaff")
class AnimeStaff : BaseJsonModel() {

    var role: String? = null

    @Relationship("anime")
    var anime: Anime? = null

    @RelationshipLinks("anime")
    var animeLinks: Links? = null

    @Relationship("person")
    var person: Producer? = null

    @RelationshipLinks("person")
    var personLinks: Links? = null

}
```

Genre.kt:
```

package app.youkai.data.models

import com.github.jasminb.jsonapi.annotations.Type

@Type("genres")
class Genre : BaseJsonModel() {

    var name: String? = null

    var slug: String? = null

    var description: String? = null

}
```

Error:
```
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to java.lang.Class

    at com.github.jasminb.jsonapi.ReflectionUtils.getFieldType(ReflectionUtils.java:64)
    at com.github.jasminb.jsonapi.ConverterConfiguration.processClass(ConverterConfiguration.java:71)
    at com.github.jasminb.jsonapi.ConverterConfiguration.registerType(ConverterConfiguration.java:293)
    at com.github.jasminb.jsonapi.ConverterConfiguration.processClass(ConverterConfiguration.java:82)
    at com.github.jasminb.jsonapi.ConverterConfiguration.registerType(ConverterConfiguration.java:293)
    at com.github.jasminb.jsonapi.ConverterConfiguration.<init>(ConverterConfiguration.java:49)
    at com.github.jasminb.jsonapi.ResourceConverter.<init>(ResourceConverter.java:88)
    at com.github.jasminb.jsonapi.ResourceConverter.<init>(ResourceConverter.java:61)
    at app.youkai.JsonParsingTests.animeStaffTest(JsonParsingTests.kt:381)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

I'd be really happy if you could share any thoughts you might have on debugging this, thanks!

**Comment by jasminb** [comment]
Hey,

Is `Anime` type extending or implementing collection interface?

This:

```
if (Collection.class.isAssignableFrom(targetType)) {}
```

Returns `true` which leads to the issue.

**Comment by dulleh** [comment]
Hi, thanks for getting back to me. The `Anime` model does not implement nor extend from collection, but it does contain many relationships of the form:

```
    @Relationship("genres")
    var genres: List<Genre>? = null

    @RelationshipLinks("genres")
    var genreLinks: Links? = null
```

Would those be problematic?

**Comment by jasminb** [comment]
Hey, It seams you have something like `List<?>`.

**Comment by dulleh** [comment]
I don't think that's the problem, however. It's not extending from it, and the code was working perfectly with those lists until recently.

```
@Type("idfxg")
class TestModelClass extends BaseJsonModel {

    @Relationship("some_relationship")
    OtherModel otherModel;

    @Relationship("list_relationship")
    List<OtherModel> otherModelList;

}
```

This class, for example, passes.

**Comment by jasminb** [comment]
So, using reflection field is resolved to be assignable to 'Collection`, after this condition is met, type needs to be resolved so it can be handled properly. Usually, if generic is typed, getting the type returns the type class object, in this case `sun.reflect.generics.reflectiveObjects.WildcardTypeImpl` is returned which causes the class cast exception. If you provide entire offending class, I might be able to provide more helpful observation. If you can reproduce the problem using dummy classes, that will also help.

**Comment by dulleh** [comment]
Ah! I've found the offending line (purely on a hunch!).

We have a model that `Anime` extends from called `Media`:

```
@Type("media")
@JsonIgnoreProperties(ignoreUnknown = true)
open class Media : BaseJsonModel() {
    . 
    //standard variable declarations
    .
    @Relationship("genres")
    var genres: List<Genre>? = null

    @RelationshipLinks("genres")
    var genreLinks: Links? = null

    @Relationship("castings")
    var castings: List<Casting>? = null

    @RelationshipLinks("castings")
    var castingLinks: Links? = null

    @Relationship("installments")
    var installments: List<Installment>? = null

    @RelationshipLinks("installments")
    var installmentLinks: Links? = null

    @Relationship("mappings")
    var mappings: List<Mapping>? = null

    @RelationshipLinks("mappings")
    var mappingLinks: Links? = null

    /*@Relationship("mediaRelationships")
    var medias: List<Media>? = null*/

    @RelationshipLinks("mediaRelationships")
    var mediaLinks: Links? = null

}
```

**Comment by dulleh** [comment]
This still works:

```
@Type("testmodelclass")
class TestModelClass extends BaseJsonModel {

    @Relationship("some_relationship")
    OtherModel otherModel;

    @Relationship("list_of_others")
    List<OtherModel> otherModelList;

    @Relationship("list_of_open_class")
    List<BaseJsonModel> baseJsonModels;

    @Relationship("list_of_self")
    List<TestModelClass> testModelClasses;

    @Relationship("list_of_media")
    List<Media> medias;
}
```

**Comment by dulleh** [comment]
@jasminb I think this is probably the clearest example of where the error is:

```
@Type("base")
open class BaseJsonModel {

    @Id
    var id: String? = null

    @Links
    var links: com.github.jasminb.jsonapi.Links? = null

    @Relationship("list_of_open_classes_within_an_open_class")
    var bases: List<BaseJsonModel>? = null

}
```

It seems to me to be a problem with having the `open` keyword in Kotlin. Any ideas?

**Comment by jasminb** [comment]
It boils down to kotlin->java interoperability. Will take a look and see if something can be done. Only thing you can do now is to use 'final' classes instead of base models.

**Comment by dulleh** [comment]
@jasminb thank you so much for the help. Sorry it boiled down to something out of your control!

For reference's sake, we created a `MediaObject` which merely extends from `Media` and use that in the relationship.

Feel free to close this issue :)

**Comment by jasminb** [comment]
Thanks for reporting, will put up a note for kotlin users for future reference.
