### ISSUE TITLE
StringIdHandler has no zero argument constructor

### ISSUE THREAD

**Issue by joaopedro1520** [jasminb/jsonapi-converter#120]
Hello,
Since you updated  the annotations to support non string ID i've been getting this crash using the 0.7 version.
Caused by: java.lang.InstantiationException: java.lang.Class<com.github.jasminb.jsonapi.StringIdHandler> has no zero argument constructor

All my model classes have empty constructors and it always worked well so far.

Any solutions?
thanks

**Comment by jasminb** [comment]
Hey,

Can you please provide a test case that reproduces the issue.

Regards

**Comment by joaopedro1520** [comment]
The error is the following  
 ```
com.github.jasminb.jsonapi.ConverterConfiguration.processClass(ConverterConfiguration.java:121)
                                                                             at com.github.jasminb.jsonapi.ConverterConfiguration.registerType(ConverterConfiguration.java:310)
                                                                             at com.github.jasminb.jsonapi.ConverterConfiguration.<init>(ConverterConfiguration.java:50)
                                                                             at com.github.jasminb.jsonapi.ResourceConverter.<init>(ResourceConverter.java:88)
                                                                             at com.github.jasminb.jsonapi.ResourceConverter.<init>(ResourceConverter.java:78)
                                                                             at com.github.jasminb.jsonapi.retrofit.JSONAPIConverterFactory.<init>(JSONAPIConverterFactory.java:50)
```

I have a bunch of classes like this 

```

@Type("battery")
public class Battery implements Parcelable {

    @Id
    private String id;

    @JsonProperty("created_at")
    private Date createdAt;

    private String identifier;

    public Battery(){}

    protected Battery(Parcel in) {
        id = in.readString();
        identifier = in.readString();
        createdAt = (Date) in.readSerializable();
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(id);
        dest.writeString(identifier);
        dest.writeSerializable(createdAt);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    public static final Creator<Battery> CREATOR = new Creator<Battery>() {
        @Override
        public Battery createFromParcel(Parcel in) {
            return new Battery(in);
        }

        @Override
        public Battery[] newArray(int size) {
            return new Battery[size];
        }
    };
```
And all the initialization of the okhttp client is as follows:

```
         ObjectMapper objectMapper = getObjectMapper();

        JacksonConverterFactory jacksonConverterFactory = JacksonConverterFactory.create(objectMapper);
        JSONAPIConverterFactory jsonapiConverterFactory = new JSONAPIConverterFactory(objectMapper, getJsonapiClasses());
        jsonapiConverterFactory.setAlternativeFactory(jacksonConverterFactory);

        OkHttpClient okHttpClient = getOKHttpClient();

        Retrofit retrofit = getRetrofit(okHttpClient, jsonapiConverterFactory, url);
        smartServices = retrofit.create(ServicesApi.SmartServices.class);
```

This setup always worked and only started crashing on start up after the last update that enables the possibility of non string Id anottation

Thanks

**Comment by jasminb** [comment]
Hey,

Are you using proguard, can you try disabling it and testing the same thing?

Regards

**Comment by joaopedro1520** [comment]
Yeah, but same thing happens with or without proguard

**Comment by jasminb** [comment]
Hey,

Could be that the reason is absence of explicit default constructor.

We can test it in two ways:
 - I will add explicit default constructor to id handler classes and update snapshot version
 - you can provide your own `StringIdHandler` implementation that has a explicit default constnructor and reconfigure your classes to use it:

```java
public class CustomIdHandler implements ResourceIdHandler {
	
	/**
	 * Creates new CustomIdHandler.
	 * 
	 */
	public CustomIdHandler() {
		// Default constructor
	}
	
	@Override
	public String asString(Object identifier) {
		if (identifier != null) {
			return String.valueOf(identifier);
		}
		return null;
	}
	
	@Override
	public String fromString(String source) {
		return source;
	}
}
```

Than using it:

```java
@Type("battery")
public class Battery implements Parcelable {

    @Id(CustomIdHandler.class)
    private String id;
```

**Comment by joaopedro1520** [comment]
So I updated to the snapshot version and that alone was not enough. Only after adding the custom ID the app stopped crashing

**Comment by jasminb** [comment]
Hey,

Could be that it takes some time for snapshot repo to start serving latest version (0.8). Please try again and let me know so I can push 0.7.1 release that fixes this issue.

Thank you for reporting and helping to resolve the issue.

Regards,
Jasmin

**Comment by joaopedro1520** [comment]
I tried again and the error is still there. I even deleted the cached dependencies but just updating to the snapshot version doesnt solve it

**Comment by jasminb** [comment]
I've downloaded snapshot version manually from sonatype repository, here are the contents for the `StringIdHandlerClass`:

```java


public class StringIdHandler
  implements ResourceIdHandler
{
  public StringIdHandler() {}
  

  public String asString(Object identifier)
  {
    if (identifier != null) {
      return String.valueOf(identifier);
    }
    return null;
  }
  
  public String fromString(String source)
  {
    return source;
  }
}
```

Sadly, it appears that there is something in your pipeline that is breaking things. If you can setup base android project that reproduces the issue and push it to github, Ill be more than happy to clone and debug the issue.

**Comment by joaopedro1520** [comment]
Just a random thought. Shouldnt you override the methods in string id handler just like in the longIdHandler?
The custom you sent me to try is also overriding the methods asString and fromString

**Comment by RezaMortazavi** [comment]
hi..i have this problem too..but the thing is it happens after adding proguard.

this is the error: 
`Caused by java.lang.InstantiationException
java.lang.Class<com.a.a.a.o> has no zero argument constructor`

 this is my proguard rule: 


```
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

-keepclassmembers class * {
    @com.github.jasminb.jsonapi.annotations.Id <fields>;
}

-keep class com.fasterxml.jackson.databind.ObjectMapper {
    public <methods>;
    protected <methods>;
}
-keep class com.fasterxml.jackson.databind.ObjectWriter {
    public ** writeValueAsString(**);
}
-keepnames class com.fasterxml.jackson.** { *; }
-dontwarn com.fasterxml.jackson.databind.**
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**
-keepattributes InnerClasses
-dontwarn okio.**
-dontwarn retrofit.**
-keep class retrofit.** { *; }
-dontwarn com.squareup.okhttp3.**
-keep class com.squareup.okhttp3.* { *;}
-dontwarn retrofit2.Platform$Java8
-keep class com.crashlytics.** { *; }
-dontwarn com.crashlytics.**
-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable
-keep class com.firebase.** { *; }
-keep class org.apache.** { *; }
-dontnote retrofit2.Platform
-keepattributes Signature
-keepattributes Exceptions
-keepattributes *Annotation*

-keep class com.A.B.common.domain.** {*;}

-keep class com.google.android.exoplayer.** {*;}

```

what am i missing?
