### ISSUE TITLE
ProGuard causes Crash.

### ISSUE THREAD

**Issue by babyblue1314** [jasminb/jsonapi-converter#176]
When using ProGuard in the file **build.gradle**:
```
android {
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
    }
    ...
}
```
I got a crash:
```
java.lang.IllegalArgumentException: All resource classes must have a field annotated with the @Id annotation
04-02 15:38:07.614 E/AndroidRuntime(20456):     at com.github.jasminb.jsonapi.ConverterConfiguration.j(ConverterConfiguration.java:119)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at com.github.jasminb.jsonapi.ConverterConfiguration.i(ConverterConfiguration.java:293)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at com.github.jasminb.jsonapi.ConverterConfiguration.<init>(ConverterConfiguration.java:49)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at com.github.jasminb.jsonapi.ResourceConverter.<init>(ResourceConverter.java:88)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at com.github.jasminb.jsonapi.ResourceConverter.<init>(ResourceConverter.java:78)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at com.ulab.newcomics.home.ui.HotPageFragment.c(HotPageFragment.java:373)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at com.ulab.newcomics.home.ui.HotPageFragment.a(HotPageFragment.java:365)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at com.cf.xinmanhua.common.BasePageFragment.b(BasePageFragment.java:40)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at com.cf.xinmanhua.common.BasePageFragment.onActivityCreated(BasePageFragment.java:20)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2193)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1323)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1969)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:620)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.View.measure(View.java:17562)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.View.measure(View.java:17562)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.ViewGroup.measureChild(ViewGroup.java:5507)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at com.cf.xinmanhua.common.CustomDrawerLayout.onMeasure(CustomDrawerLayout.java:76)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.View.measure(View.java:17562)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.View.measure(View.java:17562)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.View.measure(View.java:17562)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.View.measure(View.java:17562)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2618)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.View.measure(View.java:17562)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2045)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1203)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1409)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1091)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5926)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.Choreographer.doCallbacks(Choreographer.java:588)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.Choreographer.doFrame(Choreographer.java:558)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:761)
04-02 15:38:07.614 E/AndroidRuntime(20456):     at android
```
However, when I don't use ProGuard in the file **build.gradle**:
```
android {
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
    }
    ...
}
```
Everything works fine.

I tried to add the following code to the file **proguard-rules.pro**:
`-keep public class com.github.jasminb.** {*;}`
but it doesn't work.

Current Version: com.github.jasminb:jsonapi-converter:0.6

**Comment by jasminb** [comment]
Hey @babyblue1314,

Looks like pro-guard messes up annotations, I would try to explicitly remove annotation removal.

There are many questions like this one on SO, like https://stackoverflow.com/questions/30078380/proguard-removing-annotations-in-android-application.

**Comment by babyblue1314** [comment]
@jasminb Thanks for your quick reply!
I tried the method mentioned in the above URL, but the issue still happens.
Here is what I have done in the file **proguard-rules.pro**:
```
-keep @com.github.jasminb.jsonapi.annotations interface * {*;}
-keep @com.github.jasminb.jsonapi.annotation.Id public class *
-keepclasseswithmembernames class * {
    @com.github.jasminb.jsonapi.* <fields>;
}
-keepclasseswithmembernames class * {
    @com.github.jasminb.jsonapi.* <methods>;
}
-keepattributes *Annotation*, Exceptions, Signature, Deprecated, SourceFile, SourceDir, LineNumberTable, LocalVariableTable, LocalVariableTypeTable, Synthetic, EnclosingMethod, RuntimeVisibleAnnotations, RuntimeInvisibleAnnotations, RuntimeVisibleParameterAnnotations, RuntimeInvisibleParameterAnnotations, AnnotationDefault, InnerClasses
-keep class com.github.jasminb.jsonapi.** {*;}
-dontwarn com.github.jasminb.jsonapi.**
```

**Comment by Kevinrob** [comment]
@babyblue1314 For my project, I have this rules:

```
# Keep jsonapi relative fields
-keepclassmembers class * {
    @com.github.jasminb.jsonapi.annotations.Id <fields>;
    @com.github.jasminb.jsonapi.annotations.Meta <fields>;
}
```

**Comment by Kevinrob** [comment]
@jasminb PR #177 😉

**Comment by jasminb** [comment]
Closing as issue was resolved and README updated with helpful information.
