### ISSUE TITLE
Class doesn't have a Type annotation error, even though the class does have one

### ISSUE THREAD

**Issue by dylwedma11748** [jasminb/jsonapi-converter#260]
My situation is a bit complicated. I'm working on a library to handle API calls to Patreon's APIv2 endpoints. I'm structuring my library similarly to the original. I've already wote *most* of the resource classes, but the error I'm getting is `Class doesn't have a Type annotation. All resource classes must be annotated with a Type annotation!` even though it does have one. I've uploaded all of the resource classes to a [repo](https://github.com/dylwedma11748/patreon-java-v2) and I've also made a [StackOverflow post](https://stackoverflow.com/questions/75839987/java-jasminb-jsonapi-class-doesnt-have-a-type-annotation-error-even-though-t) explaining it in more detail.

The stacktrace I'm getting is:
`Exception in thread "main" java.lang.IllegalArgumentException: Class [Lpatreon.java.v2.resources.Campaign; doesn't have a Type annotation. All resource classes must be annotated with a Type annotation!
	at com.github.jasminb.jsonapi.ConverterConfiguration.processClass(ConverterConfiguration.java:168)
	at com.github.jasminb.jsonapi.ConverterConfiguration.registerType(ConverterConfiguration.java:310)
	at com.github.jasminb.jsonapi.ConverterConfiguration.processClass(ConverterConfiguration.java:83)
	at com.github.jasminb.jsonapi.ConverterConfiguration.registerType(ConverterConfiguration.java:310)
	at com.github.jasminb.jsonapi.ConverterConfiguration.<init>(ConverterConfiguration.java:50)
	at com.github.jasminb.jsonapi.ResourceConverter.<init>(ResourceConverter.java:93)
	at com.github.jasminb.jsonapi.ResourceConverter.<init>(ResourceConverter.java:83)
	at patreon.java.v2.PatreonAPI.<init>(PatreonAPI.java:70)
	at patreon.java.v2.PatreonAPI.<init>(PatreonAPI.java:60)
	at patreon.java.v2.PatreonAPITest.main(PatreonAPITest.java:8)`

I've found that at stack "ConverterConfiguration.processClass(Class<?>) line: 83", targetType is set to Campaign, but clazz is set to Address:

![variables](https://user-images.githubusercontent.com/32218999/227733576-651870f3-4708-4ece-9164-80af531fb68a.PNG)

In the Address class, the only reference to the Campaign class is an Array of Campaigns with a Relationship annotation:
``` java
@Type("address")
public class Address extends BaseResource {
    ...
    @Relationship("campaigns")
    private Campaign[] campaigns;
}
```

**Comment by jasminb** [comment]
Will take a look next week hopefully. Thank you for reporting!

**Comment by dylwedma11748** [comment]
Not a problem. There's no rush, as this is a personal project.

**Comment by dylwedma11748** [comment]
Found out that it was the arrays causing it, I guess for some reason when you use a resource class that has a Type annotation in an array, it doesn't work or something... I don't know. I replaced the arrays with Lists instead.
