### ISSUE TITLE
Retrofit cannot create converter for JSONAPIDocument<List<Model>>

### ISSUE THREAD

**Issue by hndmrsh** [jasminb/jsonapi-converter#50]
Hi,

I have just updated to version 0.4-SNAPSHOT of the library, and I am trying to use the JSONAPIDocument capture the metadata of resource collections. However, this does not seem to work with Retrofit:

```
Caused by: java.lang.IllegalArgumentException: Unable to create converter for com.github.jasminb.jsonapi.JSONAPIDocument<java.util.List<com.my.package.Model>>
   for method CheckInsEndpoint.retrieveCheckInsCall
   at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:720)
   at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:706)
   at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:167)
   at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
   at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
   at java.lang.reflect.Proxy.invoke(Proxy.java:813)
   at $Proxy5.retrieveCheckInsCall(Unknown Source)
   at com.my.package.HomeFeedPresenter$1.call(HomeFeedPresenter.java:149)
   at com.my.package.HomeFeedPresenter$1.call(HomeFeedPresenter.java:146)
   at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   	... 9 more
Caused by: java.lang.ClassCastException: libcore.reflect.ParameterizedTypeImpl cannot be cast to java.lang.Class
   at com.github.jasminb.jsonapi.retrofit.RetrofitType.<init>(RetrofitType.java:23)
   at com.github.jasminb.jsonapi.retrofit.JSONAPIConverterFactory.responseBodyConverter(JSONAPIConverterFactory.java:45)
   at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:325)
   at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:308)
   at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:704)
   	... 18 more
```

It appears that the `JSONAPIConverterFactory` cannot handle nested parameterized types - it assumes that the top-level Type (in this case, JSONAPIDocument) is a collection, and the parameterized type is the actual type.

I have also tried this with the 0.3 release (using [this Retrofit 2 adapter](https://github.com/team-rawbot/jsonapi-retrofit2-adapter)) with the same outcome.

**Comment by hndmrsh** [comment]
Hi,

Would very much appreciate an update on this issue if possible, as it is preventing me from updating from v0.2. Is the issue clear enough, or do you need more information?

**Comment by jasminb** [comment]
Hey,

Will check it out and update you.

**Comment by jasminb** [comment]
Hey, would you be willing to checkout a branch, build it yourself and see it this is what you need?

Gist of this change is actually aligning the retrofit plugin with changes in `ResourceConverter` itself (instead of returning raw types, conversion methods now return `JSONAPIDocument<?>`)?

Example service:

```
public interface SimpleService {

	@GET("user")
	Call<JSONAPIDocument<User>> getExampleResource();

	@GET("users")
	Call<JSONAPIDocument<List<User>>> getExampleResourceList();

	@GET("notanjsonapiendpoint")
	Call<ErrorResponse> getNonJSONSPECResource();

	@POST("user")
	Call<JSONAPIDocument<User>> createUser(@Body User user);
}
```

Branch: `retrofit-type-alignment`

**Comment by hndmrsh** [comment]
Hey @jasminb , thanks for looking into a fix - I will give it a go and see if this solves my issues next week.

**Comment by hndmrsh** [comment]
@jasminb: your proposed fix seems to solve the issues - thanks!

**Comment by hndmrsh** [comment]
The only potential issue with this solution is that it automatically wraps all responses in a `JSONAPIDocument`, which may not be the desired behaviour. For example, the service `Response<MyModel>` (in my case I am using the Rx extensions for Retrofit, so my service is actually `Observable<Response<MyMode>>`) returns an object of type `Response<JSONAPIDocument<MyModel>>`. This shouldn't be a problem in my case, but as far as I can tell, this is not the expected behaviour. The same behaviour occurs with `Response<List<MyModel>>` - an object of type `Response<JSONAPIDocument<List<MyModel>>>` is always returned.

**Comment by jasminb** [comment]
Hey,

I will give it some more thought. Latest contracts from `ResourceConverter` actually use the same approach (wrapping objects into `JSONAPIDocument`, this is needed since there are `response` level details (meta and links) which are not part of the resource itself.

I will see to adapt the solution so it works with with and without wrapping (depending on service declared types).

**Comment by jasminb** [comment]
Fixed with #57. @hndmrsh please check snapshot version and close the issue.

**Comment by hndmrsh** [comment]
Hey, this seems to work now, but it has introduced a regression: the constructor `public JSONAPIConverterFactory(ObjectMapper mapper, Class... classes)` does not instantiate the `serializer` field with a `ResourceConverter`, which causes serialization of request bodies for `POST` calls to fail.

Let me know if you need me to explain further!

**Comment by jasminb** [comment]
Thanks for reporting it @hndmrsh, I've fixed it and pushed to `develop`.

**Comment by hndmrsh** [comment]
Great! All working now, cheers.
