### ISSUE TITLE
Mixed type/ type wildcard/ polymorphism

### ISSUE THREAD

**Issue by ericn37** [jasminb/jsonapi-converter#78]
My server search API returns a list of object of various types e.g. "products", "brands" etc.

I have Product and Brand model both extending BaseModel:
```
public class BaseModel {
    @Id
    protected String id;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}
```

I've tried the following:
```
public interface SearchService {
    SearchService serviceJasminb = MyRESTClient.retrofitJasminb.create(SearchService.class);

    @GET("search")
    Call<JSONAPIDocument<ArrayList<? extends BaseModel>>> search(@Query("query") String query);
```
but I got the following exception:
```
java.lang.IllegalArgumentException: Method return type must not include a type variable or wildcard: retrofit2.Call<com.github.jasminb.jsonapi.JSONAPIDocument<java.util.ArrayList<? extends com.xxx.yyy.models.BaseModel>>>
                                                     for method SearchService.retrieveSearch
                                                     at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:720)
                                                     at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:711)
                                                     at retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:224)
                                                     at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:160)
                                                     at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
                                                     at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
                                                     at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                     at $Proxy16.retrieveSearch(Unknown Source)
                                                     at com.xxx.yyy.caches.SearchCache.fetchSearch(SearchCache.java:187)
                                                     at com.xxx.yyy.views.activities.SearchActivity.run(SearchActivity.java:352)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by jasminb** [comment]
Hey @ericn37, error you got is related to retrofit. Why not use `BaseType` only?

**Comment by emetsger** [comment]
I don't have much to add to this conversation, except to add a "me too".
I'm working with a JSON API that has relationships that can point to
objects of different types.

For example, an object may have a  relationship named `somerel` with a
`related` link to `http://example.org/resource/1`, and the JSON
representation at http://example.org/resource/1 may have a `type` of `Baz`.

A different object may express a relationship named `somerel` with a
`related` link to `http://example.org/resource/2`, and the JSON
representation http://example.org/resource/2 may have a `type` of `Biz`.

The semantics of the relationship named `somerel` hold for these two
example objects, even though dereferencing the link returns objects of
different types.

This becomes problematic when you are dereferencing `somerel`: you may
retrieve objects typed as `Biz` or objects typed as `Baz`:

```
@Type("foo")
public class Foo {
  @Relationship(value = "somerel", resolve = true)
  private Biz field;

  // ....
}
```

This class can't be used to deserialize `somerel` where the type is `Baz`;
it only works for type `Biz`.

One option is to have `Baz` and `Biz` share a super-type, and update the
java class as follows:
Baz -- extends --> BaseObject
Biz -- extends --> BaseObject

```
@Type("foo")
public class Foo {
  @Relationship(value = "somerel", resolve = true)
  private BaseObject field;

  // ....
}
```

However, that does not work either.  You must deserialize a concrete type
(either `Baz` or `Biz`) which fails, before assigning to a base class.

I am not sure if this is a Retrofit problem or a jsonapi-converter problem,
or what.  But currently the semantics of a relationship are coupled to the
type of object returned by that relationship, which is unfortunate.

**Comment by Servus7** [comment]
@emetsger It's an jsonapi-converter problem. Other libraries like [moshi-jsonapi](https://github.com/kamikat/moshi-jsonapi) are able to convert different types.

**Comment by ericn37** [comment]
https://github.com/faogustavo/JSONApi is also able to parse multiple types.
It used to be my favourite.
Their drawback is that they are are not be to handle circular reference properly 😭 

However, is it a tradeoff?
Multiple types/ polymorphism ==> no circular reference
Circular reference (this libary) ==> no multiple types/ polymorphism

**Comment by ericn37** [comment]
@jasminb I've tried what you suggested, however, I only got `BaseModel` object, not the subclass.
When I try to cast, I got `ClassCastException`
```
Process: com.xxx.yyy, PID: 10629
                                                 java.lang.ClassCastException: com.xxx.yyy.models.BaseModel cannot be cast to com.xxx.yyy.models.LandingPagePromoList
                                                     at com.xxx.yyy.tasks.LandingPageTask$1.onResponse(LandingPageTask.java:35)
                                                     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by jasminb** [comment]
Hey,

What version of the lib you are using. Support for providing base type is SNAPSHOT only and not yet part of any release. Until new release is out, please use latest snapshot (example in the README).

**Comment by ericn37** [comment]
Hi @jasminb , I'm using 0.4. Will try the snapshot. Thanks :)

**Comment by jasminb** [comment]
Hey @ericn37, did 0.5 solve the issue for you?

**Comment by ericn37** [comment]
Yes, indeed 0.5 did solve the problem, thanks @jasminb
